version: '3.7'
services: 
  postgres: 
    image: postgres:15-alpine
    restart: always 
    container_name: nest-postgres

    environment: 
      - POSTGRES_DB=second_brain
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=twisteromega 
    ports: 
      - "5433:5432"
    networks: 
      - prisma-network 
    
    volumes: 
      - postgres_data:/var/lib/postgresql/data 
    command: postgres -c listen_addresses='*' 

networks: 
  prisma-network: 
volumes: 
  postgres_data: 